# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test V3

on:
  push:
    branches: [ gpu-buffer-implementation ]
  pull_request:
    branches: [ v3 ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: py=${{ matrix.python-version }}, np=${{ matrix.numpy-version }}, deps=${{ matrix.dependency-set }}

    runs-on: "cirun-aws-g4dn-xlarge-nvidia-ubuntu2204--${{ github.run_id }}"
    strategy:
      matrix:
        python-version: ['3.10',]
        numpy-version: ['1.24',]
        dependency-set: ["minimal"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: NVIDIA SMI Sanity check
      run: nvidia-smi
    - name: Install Hatch
      run: |
        python -m pip install --upgrade pip 
        pip install hatch
    - name: Set Up Hatch Env
      run: |
        hatch env create test.py${{ matrix.python-version }}-${{ matrix.numpy-version }}-${{ matrix.dependency-set }}
        hatch env run -e test.py${{ matrix.python-version }}-${{ matrix.numpy-version }}-${{ matrix.dependency-set }} list-env
    - name: Run Tests
      run: |
        hatch env run --env test.py${{ matrix.python-version }}-${{ matrix.numpy-version }}-${{ matrix.dependency-set }} run
